# errors.py

ERRORS = [
    "ArithError",
    "BothNotBool",
    "RepeatedValue",
    "assignError",
    "methodValuesNotSame",
    "NotSameLength",
    "TypeNotExist",
    "notContainsType",
    "differentMethodType",
    "differentReceivers",
    "recursiveInherit",
    "whileError",
    "DoubleMain",
    "newError",
    "invertNotInt",
    "inheritProblem",
    "noMain",
    "boolAr",
    "intchar",
    "charAr",
    "assignEr",
    "notEqual",
    "noValue",
    "ifError",
    "notLessOrEqual",
    "notLess",
    "methodError",
    "noMethodAssign",
]
